class Foto{
  constructor(){
    this.mostrar=this.mostrar.bind(this);
    this.stopPropagation=this.stopPropagation.bind(this);
    this.hide=this.hide.bind(this);
    this.transitioenEnd=this.transitioenEnd.bind(this);
    this.optionsPerfil=document.querySelector("#optionsPerfil");
    this.foto=document.querySelector("#fotoMenu1");
    this.comenzar();
  }
  comenzar(){
    this.foto.addEventListener("click",this.mostrar);
  }
  stopPropagation(e){
    e.stopPropagation();
  }
  transitioenEnd(){
    this.optionsPerfil.style="none";
  }
  mostrar(e){
    if(this.foto.dataset.active=="true"){
      this.hide();
      return
    }
    this.optionsPerfil.removeEventListener("transitionend",this.transitioenEnd);
    this.foto.dataset.active="true";
    this.optionsPerfil.style.display="grid";
    this.optionsPerfil.addEventListener("click",this.stopPropagation);
    requestAnimationFrame(()=>{
      requestAnimationFrame(()=>{
        this.optionsPerfil.style.transform="translateX(-210px)";
        document.body.addEventListener("click",this.hide,{once:true});
      });
    });
  }
  hide(e){
    this.optionsPerfil.addEventListener("transitionend",this.transitioenEnd,{once:true});
    this.optionsPerfil.style.transform="translateX(0)";
    this.foto.dataset.active="false";
    this.optionsPerfil.removeEventListener("click",this.stopPropagation);
    document.body.removeEventListener("click",this.hide);
  }
}
let foto=new Foto();